credits_app/credits/urls.py
from django.urls import path, include

from . import views

app_name = "contracts"

urlpatterns = [
    path('', views.home, name='home'),
    path("createcontract", views.createcontract, name="createcontract"),
    path("contracts-list", views.contract_list, name="contract_list"),
    path("manufacturers-list", views.manufacturers_list, name="manufacturers_list"),
    path("manufacturers-create", views.create_manufacturers, name="create_manufacturers"),
    path("products-list", views.products_list, name="products_list"),
    path("product-create", views.create_product, name="create_product"),
    path("loanrequests-list", views.loanrequests_list, name="loanrequests_list"),
    path("loanrequest-create", views.create_loanrequests, name="create_loanrequests"),
]

credits_app/credits_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('credits.urls', namespace='credits')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credits_app/credits/models.py
from django.db import models

from .mixins import TimestampableMixin, StartEndDateMixin


class LoanRequest(TimestampableMixin, StartEndDateMixin):
    """Кредитные заявки"""
    number = models.CharField("Номер кредитной заявки", max_length=250)
    contract = models.OneToOneField("Contract", verbose_name="Контракт", related_name="loan_request",
                                    on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Кредитная заявка"
        verbose_name_plural = "Кредитные заявки"

    def __str__(self):
        return self.number


class Contract(TimestampableMixin, StartEndDateMixin):
    """Контракты"""
    number = models.IntegerField("Номер контракта", unique=True)

    class Meta:
        verbose_name = "Номер контракта"
        verbose_name_plural = "Номера контрактов"

    def __str__(self):
        return f"Контракт №{self.number}"


class Product(TimestampableMixin, StartEndDateMixin):
    """Товары"""
    name = models.CharField("Наименование товара", max_length=250)
    loan_request = models.ForeignKey("LoanRequest", verbose_name="Кредитная заявка", related_name="products",
                                     on_delete=models.CASCADE, blank=True, null=True)
    manufacturer = models.ForeignKey("Manufacturer", verbose_name="Производитель", related_name="products",
                                     on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Наименование товара"
        verbose_name_plural = "Наименование товаров"

    def __str__(self):
        return self.name


class Manufacturer(TimestampableMixin, StartEndDateMixin):
    """Производители"""
    name = models.CharField("Производитель", max_length=250)

    class Meta:
        verbose_name = "Производитель"
        verbose_name_plural = "Производители"

    def __str__(self):
        return self.name

credits_app/credits/forms.py
from django import forms

from . import models


class CreateContractForm(forms.ModelForm):

    class Meta:
        model = models.Contract
        fields = ("number",)


class CreateManufacturerForm (forms.ModelForm):

    class Meta:
        model = models.Manufacturer
        fields = ("name",)


class CreateProductForm (forms.ModelForm):
    loan_request = forms.ModelChoiceField(queryset=models.LoanRequest.objects.all(), required=False)

    class Meta:
        model = models.Product
        fields = ("name", "manufacturer", "loan_request")


class CreateLoanRequestsForm (forms.ModelForm):
    contract = forms.ModelChoiceField(queryset=models.Contract.objects.filter(loan_request__isnull=True))

    class Meta:
        model = models.LoanRequest
        fields = ("number", "contract",)


class SearchManufacturerForm(forms.Form):
    number = forms.IntegerField(label="Id контракта", min_value=0, required=True)

credits_app/credits/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from . import forms, models


def home(request):
    form = forms.SearchManufacturerForm(request.POST or None)
    context = {"form": form}
    if request.method == "POST" and form.is_valid():
        contract_id = request.POST.get('number')
        manufacturers = models.LoanRequest.objects.filter(contract_id=contract_id).exclude(
            products__manufacturer_id__isnull=True).values_list(
            'products__manufacturer_id', flat=True).distinct()
        if manufacturers:
            context["manufacturers"] = manufacturers
        else:
            context["error"] = "Не найдено ни одного производителя для данной кредитной заявки."
    return render(request, 'list.html', context)


def contract_list(request):
    contracts = models.Contract.objects.all()
    return render(request, "contract/list.html", {"contracts": contracts})


def createcontract(request):
    form = forms.CreateContractForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse("contracts:contract_list"))
    context = {"form": form}
    return render(request, "contract/create.html", context)


def create_manufacturers(request):
    form = forms.CreateManufacturerForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse("contracts:manufacturers_list"))
    context = {"form": form}
    return render(request, "manufacturer/create.html", context)


def manufacturers_list(request):
    manufacturers = models.Manufacturer.objects.all()
    return render(request, "manufacturer/list.html", {"manufacturers": manufacturers})


def products_list(request):
    products = models.Product.objects.all()
    return render(request, "product/list.html", {"products": products})


def create_product(request):
    form = forms.CreateProductForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse("contracts:products_list"))
    context = {"form": form}
    return render(request, "product/create.html", context)


def loanrequests_list(request):
    loanrequests = models.LoanRequest.objects.all()
    return render(request, "loanrequest/list.html", {"loanrequests": loanrequests})


def create_loanrequests(request):
    if models.Contract.objects.filter(loan_request__isnull=True):
        form = forms.CreateLoanRequestsForm(request.POST or None)
        context = {"form": form}
        if request.method == "POST" and form.is_valid():
            form.save()
            return redirect(reverse("contracts:loanrequests_list"))
    else:
        context = {"error": "Для контракта возможна только одна кредитная заявка. Пожалуйста, создайте новый контракт."}

    return render(request, "loanrequest/create.html", context)

credits_app/templates/contract/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Добавить контракт</h2>
<form method="post">
    {% csrf_token %}
    {{ form.number }}
    <input type="submit" value="Добавить">
    <a href="{{ BACK_URL }}">Назад</a>
</form>
</body>
</html>

credits_app/templates/contract/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Контракты</h2>
<div>

    <a href="{% url 'contracts:createcontract' %}">Создать</a>
</div>
<table>
    <thead>
    <tr>
        <th>Номер контракта</th>
        <th>Дата создания</th>
    </tr>
    </thead>

    <tbody>
    {% for contract in contracts %}
    <tr>
        <td>{{ contract.number }}</td>
        <td>{{ contract.created_at|date:'d.m.Y' }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{{ BACK_URL }}">Назад</a>
</body>
</html>

credits_app/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Button Click Demo</title>
</head>
<body>

<h1>Выберите одну из опций:</h1>

<div>
    <a href="{% url 'contracts:contract_list' %}" class="button">Контракты</a>
    <a href="{% url 'contracts:manufacturers_list' %}" class="button">Производители</a>
    <a href="{% url 'contracts:products_list' %}" class="button">Товары</a>
    <a href="{% url 'contracts:loanrequests_list' %}" class="button">Кредитные заявки</a>
</div>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Поиск">
    <a class="btn btn-primary" href="#" title="Просмотр"></a>
</form>
<div>
    {% if manufacturers %}
    <h3>Уникальные ID производителей:</h3>
    <ul>
        {% for id in manufacturers %}
        <li>{{ id }}</li>
        {% endfor %}
    </ul>
    {% elif error %}
    <p>{{ error }}</p>
    {% endif %}
</div>

</body>
</html>

credits_app/templates/loanrequest/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Добавление кредитной заявки</h2>
{% if form %}
    <form method="post">
        {% csrf_token %}
        {{ form.number }}
        {{ form.contract }}
        <input type="submit" value="Добавить">
        <a href="{{ BACK_URL }}">Назад</a>
    </form>
{% else %}
    <p>{{ error }}</p>
{% endif %}
</body>
</html>

credits_app/templates/loanrequest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Кредитные заявки</h2>

<div>

    <a href="{% url 'contracts:create_loanrequests' %}">Создать</a>
</div>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Номер</th>
        <th>Контракт</th>
        <th>Дата создания</th>
    </tr>
    </thead>

    <tbody>
    {% for loanrequest in loanrequests %}
    <tr>
        <td>{{ loanrequest.id }}</td>
        <td>{{ loanrequest.number }}</td>
        <td>{{ loanrequest.contract }}</td>
        <td>{{ loanrequest.created_at|date:'d.m.Y' }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{{ BACK_URL }}">Назад</a>
</body>
</html>

credits_app/templates/manufacturer/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Товары</h2>
<div>

    <a href="{% url 'contracts:create_product' %}">Создать</a>
</div>
<table>
    <thead>
    <tr>
        <th>Наименование товара</th>
        <th>Производитель</th>
        <th>Кредитная заявка</th>
        <th>Дата создания</th>
    </tr>
    </thead>

    <tbody>
    {% for product in products %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.manufacturer }}</td>
        <td>{{ product.loan_request | default:'----'  }}</td>
        <td>{{ product.created_at|date:'d.m.Y' }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{{ BACK_URL }}">Назад</a>
</body>
</html>

credits_app/templates/manufacturer/list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<h2>Производители</h2>

<div>

    <a href="{% url 'contracts:create_manufacturers' %}">Создать</a>
</div>
<table>
    <thead>
    <tr>
        <th>Производители</th>
        <th>Дата создания</th>
    </tr>
    </thead>

    <tbody>
  {% for manufacturer in manufacturers %}
    <tr>
        <td>{{ manufacturer.name }}</td>
        <td>{{ manufacturer.created_at|date:'d.m.Y' }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{{ BACK_URL }}">Назад</a>
</body>
</html>

credits_app/templates/product/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<h2>Добавление товара</h2>
<form method="post">
    {% csrf_token %}
    {{ form.name }}
    {{ form.manufacturer }}
    <input type="submit" value="Добавить">
    <a href="{{ BACK_URL }}">Назад</a>
</form>
</body>
</html>

credits_app/templates/product/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Товары</h2>
<div>

    <a href="{% url 'contracts:create_product' %}">Создать</a>
</div>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Наименование товара</th>
        <th>Производитель</th>
        <th>Дата создания</th>
    </tr>
    </thead>

    <tbody>
    {% for product in products %}
    <tr>
        <td>{{ product.id }}</td>
        <td>{{ product.name }}</td>
        <td>{{ product.manufacturer }}</td>
        <td>{{ product.created_at|date:'d.m.Y' }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{{ BACK_URL }}">Назад</a>
</body>
</html>